---
title: "Calculating Blockiness from Exeter Data"
author: "Bryan"
date: "September 20, 2021"
output: rmarkdown::github_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
# install.packages("magick")
library(magick)
```

## Read in datasets, merge, and split out accession names

```{r}
setwd("~/projects/RScripts/Blockiness")
exeter_header <- read.csv("exeter_header.csv", header = FALSE, check.names = TRUE,  stringsAsFactors = FALSE)
blockiness_controls <- read.csv("blockiness_controls.csv", header = FALSE, check.names = TRUE,  stringsAsFactors = FALSE)
colnames(blockiness_controls) <- head(exeter_header, 1)
plot_data <- read.csv("2020allrootsv2.csv", header = TRUE, check.names = TRUE,  stringsAsFactors = FALSE)
common_cols <- intersect(colnames(blockiness_controls), colnames(plot_data))
data <- rbind(
  blockiness_controls[common_cols], 
  plot_data[common_cols]
)

identifiers <- strcapture(
  "(^[^_]+)_([^_]+)_([^_]+)_(.*)",
  as.character(data$plot_name),
  data.frame(trial = character(), plotnum = character(), rep = character(), accession = character())
)
data <- cbind(identifiers, data)
```

## Calculate blockiness

```{r}
# convert hundreths of inch to cm and 10ths of ounces to grams
data$diametercm <- as.numeric(data$diameter) * 0.0254 # cm per 1/100 inch
data$lengthcm <- as.numeric(data$length) * 0.0254 # cm per 1/100 inch
data$weightg <- as.numeric(data$weight) * 2.8349523 # g per 1/10 ounce

# calculate max cylindrical volume in cubic cenimeters
data$max.volumecc <- pi * (as.numeric(data$diametercm)/2)^2 * as.numeric(data$lengthcm)  # cyclindrical volume = pi*r2*h

# Exeter estimates a density of 0.93 g per cm3
# calculate blockiness as ratio of estimated volume (weight in grams / 0.93 g per cm3)  to maximum theoretical volume
# 1 = perfectly blockly (all of possible cylindrical volume filled), 0 = infinitely not blocky (none of possible cylindrical volume filled)
blockiness <- (data$weightg / 0.93) / data$max.volumecc
data <- cbind(blockiness, data)

```

## Create blockiness illustration

```{r}
example <- image_read('blocky_positive_control_NIR_V1_O0001.tif')
example <-image_crop(example, "400x480+25+200")
extra <- image_crop(example, "100x600+300+0")
joined <- c(example,extra,extra,extra)
expanded <- image_append(joined)
expanded <- image_draw(expanded)
segments(x0 = 130, y0 = 40, x1 = 130, y1 = 425, col="green")
segments(x0 = 60, y0 = 250, x1 = 200, y1 = 250, col="green")
text(125, 30, "Length = 14.9cm", family = "monospace", cex = 1, col="green")
text(65, 240, "Diameter = 6.0cm", family = "monospace", cex = 1, col="green")
text(125, 450, "Est. Weight = 380g", family = "monospace", cex = 1, col="green")

text(450, 75, "If an ideally blocky root is a perfect cylinder, then a blockiness score (B) can be
calculated as the ratio of actual volume (V) to potential cylindrical volume (pi * r^2 * h)", family = "monospace", cex = 1, col="white")

text(450, 125, expression(B == V %/% (pi~'*'~'r^2'~'*'~h)), cex=2, col="green")

text(450, 175, "The density of a sweetpotato is nearly the same as water, or 1 g/cm3.
So weight in grams is a good approximation of volume in cm3", family = "monospace", cex = 1, col="white")

text(450, 225, expression(B == '380cm3' %/% (pi~'*'~'r^2'~'*'~h)), cex=2, col="green")

text(450, 275, "The Exeter grader produces an estimated length and diameter, which can be
converted to cm. Root length in cm is equivalent to cylinder height (h),
and 1/2 of the diameter is equivalent to cylinder radius (r)", family = "monospace", cex = 1, col="white")

text(450, 325, expression(B == '380cm3' %/% (pi~'*'~'(3cm)^2'~'*'~'14.9cm')), cex=2, col="green") 

text(450, 375, "Finally, solving for B gives a 'Blockiness' score between 1 and 0", family = "monospace", cex = 1, col="white")

text(450, 425, expression({B ==  '380cm3' %/% '421cm3'} == '0.90'), cex=2, col="green")
dev.off()

```

# Filter out all but No1 roots and Jumbos

```{r}
# Remove canners and culls by keeping only roots with diam >= 200 and length >= 299 and weight >=50
No1s_and_Jumbos <- data[data$trial == "21BLOK0002HCR" | (data$diameter >= 200 & data$length >= 300 & data$weight >= 50),]

# Set No1s as remaining roots with diam <= 350 and length <= 900 and weight <=220
No1s <- No1s_and_Jumbos[No1s_and_Jumbos$trial == "21BLOK0002HCR" | (No1s_and_Jumbos$diameter <= 350 & No1s_and_Jumbos$length <= 900 & No1s_and_Jumbos$weight <= 220),] 

# Set Jumbos as remaining roots with diam > 350 or length > 900 or weight > 220
Jumbos <- No1s_and_Jumbos[No1s_and_Jumbos$trial == "21BLOK0002HCR" | (No1s_and_Jumbos$diameter > 350 | No1s_and_Jumbos$length > 900 | No1s_and_Jumbos$weight > 220),]
```

# Draw blockiness boxplots 

```{r}

average_colors <- function(indiv_colors) {
  print(indiv_colors)
  reds<- substr(indiv_colors, 1, 2)
  greens<- substr(indiv_colors, 3, 4)
  blues<- substr(indiv_colors, 5, 6)
  rsquared <- strtoi(reds, base=16)^2
  gsquared <- strtoi(greens, base=16)^2
  bsquared <- strtoi(blues, base=16)^2
  return(
    rgb(
      round(sqrt(mean(rsquared))),
      round(sqrt(mean(gsquared))),
      round(sqrt(mean(bsquared))),
      maxColorValue=255
    )
  )
}

# Adjust plot size to fit vertical x labels
par(mar=c(10,5,4,2))

# Create trial specific title and retrieve subset of data from trial of interest
trialname <- "20FFMC0040HCRN11"
title <- paste(trialname, "No1 and Jumbo Blockiness", sep=" ") 
FFMC <- No1s_and_Jumbos[No1s_and_Jumbos$trial == "21BLOK0002HCR" | No1s_and_Jumbos$trial == "20FFMC0040HCRN11",]

# Order accession by mean blockiness and calculate avg skin color
FFMC$accession <- with(FFMC, reorder(accession , -blockiness, median , na.rm=T))
plot_colors <- tapply(as.hexmode(substr(FFMC$colorhex1, 2, nchar(FFMC$colorhex1))), FFMC$accession, average_colors)

# Create plot and add repositioned X axis title
b <- boxplot(blockiness ~ accession, data=FFMC, main=title, ylab=expression(bold("Blockiness")), las=2, col=plot_colors, xaxt="n", xlab="")
title(xlab= "Accession", line=6, cex.lab=1, family="Calibri Light", adj=0.45, font.lab = 2)

# Add sample sizes and tilted x-axis labels
text(seq_along(na.omit(unique(FFMC$accession))), b$stats[3,] + 0.012, paste("n=", b$n))
text(unique(FFMC$accession), par("usr")[3] - .05, labels = unique(FFMC$accession), srt = 45, adj = 1, xpd = TRUE);
```

# Match representative root photos with blockiness scores

```{r}

pc <- image_read('blocky_positive_control_RGB_V1_O0001.tif')
pc <-image_crop(pc, "300x500+50+200")
pc <-image_scale(pc, 150)
pc <- image_draw(pc)
rect(17, 23, 90, 210, border = "green", lty = "dashed", lwd = 2)
text(60, 235, "B = 0.90", family = "monospace", cex = 1, col="green")

nc <- image_read('blocky_negative_control_RGB_V1_O0002.tif')
nc <-image_crop(nc, "300x500+50+25")
nc <-image_scale(nc, 150)
nc <- image_draw(nc)
rect(25, 37, 97, 197, border = "green", lty = "dashed", lwd = 2)
text(60, 230, "B = 0.13", family = "monospace", cex = 1, col="green")

BB1 <- image_read('plot_data/Bbelle-05/Images/Bbelle-05_single_RGB_V1_O0253.tif')
BB1 <-image_crop(BB1, "300x500+15+0")
BB1 <-image_scale(BB1, 150)
BB1 <- image_draw(BB1)
rect(11, 5, 112, 184, border = "green", lty = "dashed", lwd = 2)
text(60, 230, "B = 0.77", family = "monospace", cex = 1, col="green")

BB2 <- image_read('plot_data/Bbelle-06/Images/Bbelle-06_single_RGB_V1_O0228.tif')
BB2 <-image_crop(BB2, "300x500+50+25")
BB2 <-image_scale(BB2, 150)
BB2 <- image_draw(BB2)
rect(30, 10, 105, 235, border = "green", lty = "dashed", lwd = 2)
text(60, 230, "B = 0.23", family = "monospace", cex = 1, col="green")

BB3 <- image_read('plot_data/Bbelle-07/Images/Bbelle-07_single_RGB_V1_O0231.tif')
BB3 <-image_crop(BB3, "300x500+60+125")
BB3 <-image_scale(BB3, 150)
BB3 <- image_draw(BB3)
rect(12, 12, 90, 225, border = "green", lty = "dashed", lwd = 2)
text(60, 240, "B = 0.61", family = "monospace", cex = 1, col="green")

all <- c(pc,BB1,BB3,BB2,nc)
all_images <- image_append(all)
all_images
```
